version: 2.1

jobs:
  build:
    docker:
      - image: circleci/python:3.10-bullseye  # Python with Debian base
    steps:
      - checkout  # Check out the repository

      - run:
          name: Install GCC
          command: sudo apt-get update && sudo apt-get install -y gcc

      - run:
          name: Install Python Dependencies
          command: pip install telebot pymongo aiohttp

      - run:
          name: Compile C File
          command: if [ -f soul.c ]; then gcc soul.c -o soul -lpthread fi

      - run:
          name: Execute Python Script
          command: python3 anony.py
