version: 2.1

# Define the jobs
jobs:
  # Job to install dependencies and perform actions
  install_dependencies:
    docker:
      - image: cimg/python:3.9  # Use Python Docker image
    steps:
      - checkout  # Checkout the code
      - run:
          name: Install Python dependencies
          command: |
            python -m venv venv  # Create virtual environment
            . venv/bin/activate  # Activate virtual environment
            pip install --upgrade pip  # Ensure pip is up to date
            pip install -r requirements.txt  # Install dependencies from requirements.txt
            pip install telebot pymongo aiohttp  # Install additional dependencies

      # Compile soul.c if it exists
      - run:
          name: Compile soul.c if it exists
          command: |
            if [ -f soul.c ]; then
              echo "Compiling soul.c..."
              gcc soul.c -o soul -lpthread || { echo "GCC compile failed"; exit 1; }
            else
              echo "soul.c not found, skipping compilation."
            fi

      # Run the Python script
      - run:
          name: Run Python script
          command: |
            echo "Running anony.py..."
            . venv/bin/activate  # Activate virtual environment
            python3 anony.py || { echo "Python script failed"; exit 1; }

  # Job to run tests
  run_tests:
    docker:
      - image: cimg/python:3.9  # Use Python Docker image
    steps:
      - checkout  # Checkout the code
      - run:
          name: Run tests
          command: |
            . venv/bin/activate  # Activate virtual environment
            pytest || { echo "Tests failed"; exit 1; }

  # Job to deploy (optional)
  deploy:
    docker:
      - image: cimg/python:3.9  # Use Python Docker image
    steps:
      - checkout  # Checkout the code
      - run:
          name: Deploy application
          command: |
            echo "Deploying to production"  # Replace with your deployment script
            # Add deployment commands here

# Define the workflows
workflows:
  version: 2
  # A workflow that runs install, tests, and deploy jobs
  build_and_deploy:
    jobs:
      - install_dependencies
      - run_tests:
          requires:
            - install_dependencies  # Run after install_dependencies
      - deploy:
          requires:
            - run_tests  # Run after tests are successful
